/*
 * pdm_specific.h
 *
 *  Created on: 24 de jan de 2023
 *      Author: Rodolfo
 */

#ifndef INC_PDM_SPECIFIC_H_
#define INC_PDM_SPECIFIC_H_

#include "main.h"
#include "pdm.h"

#define PDM_INPUT_GPIO	{GPIOF, GPIOF, GPIOF, GPIOF, GPIOB, GPIOB, GPIOC, GPIOC, GPIOC, GPIOC, GPIOC, GPIOC, GPIOB, GPIOB, GPIOB, GPIOB}

#define PDM_INPUT_PIN	{GPIO_PIN_0, GPIO_PIN_1, GPIO_PIN_2, GPIO_PIN_3, GPIO_PIN_4, GPIO_PIN_5, GPIO_PIN_6, GPIO_PIN_7, GPIO_PIN_8, GPIO_PIN_9, GPIO_PIN_10, GPIO_PIN_11, GPIO_PIN_12, GPIO_PIN_13, GPIO_PIN_14, GPIO_PIN_15}

#define PDM_OUTPUT_GPIO	{GPIOB, GPIOB, GPIOB, GPIOE, GPIOD, GPIOD, GPIOD, GPIOD, GPIOD, GPIOD, GPIOD, GPIOD, GPIOG, GPIOG, GPIOG, GPIOG}

#define PDM_OUTPUT_PIN	{GPIO_PIN_1, GPIO_PIN_0, GPIO_PIN_10, GPIO_PIN_14, GPIO_PIN_9, GPIO_PIN_8, GPIO_PIN_11, GPIO_PIN_10, GPIO_PIN_13, GPIO_PIN_12, GPIO_PIN_15, GPIO_PIN_14, GPIO_PIN_3, GPIO_PIN_2, GPIO_PIN_5, GPIO_PIN_4}

#define PDM_OUT_TYPES	{Output_PWM, Output_PWMN, Output_PWM, Output_PWM, Output_GPIO, Output_GPIO, Output_GPIO, Output_GPIO, Output_GPIO, Output_GPIO, Output_GPIO, Output_GPIO, Output_GPIO, Output_GPIO, Output_GPIO, Output_GPIO}
#define PDM_PWM_OUTPUTS		0x000f

#define PDM_EEPROM_PT1_SIZE	100
#define PDM_EEPROM_PT2_SIZE	100

#endif /* INC_PDM_SPECIFIC_H_ */
